"""Prompts for all stages of the investment analysis pipeline."""

# Argument Generation Prompts
from agent.prompts.argument_generation import (
    ARGUMENT_GENERATION_SYSTEM_PROMPT,
    CONTRA_ARGUMENTS_USER_PROMPT,
    PRO_ARGUMENTS_USER_PROMPT,
)

# Argument Critique Prompts
from agent.prompts.argument_critique import (
    DEVILS_ADVOCATE_CONTRA_SYSTEM_PROMPT,
    DEVILS_ADVOCATE_INDIVIDUAL_CONTRA_ARGUMENT_USER_PROMPT,
    DEVILS_ADVOCATE_INDIVIDUAL_PRO_ARGUMENT_USER_PROMPT,
    DEVILS_ADVOCATE_PRO_SYSTEM_PROMPT,
)

# Argument Evaluation Prompts
from agent.prompts.argument_evaluation import (
    CRITERIA_MAPPING,
    EVALUATE_SINGLE_ARGUMENT_USER_PROMPT,
    SINGLE_ARGUMENT_EVALUATION_SYSTEM_PROMPT,
)

# Argument Refinement Prompts
from agent.prompts.argument_refinement import (
    REFINE_CONTRA_ARGUMENT_SYSTEM_PROMPT,
    REFINE_CONTRA_ARGUMENTS_USER_PROMPT,
    REFINE_PRO_ARGUMENT_SYSTEM_PROMPT,
    REFINE_PRO_ARGUMENTS_USER_PROMPT,
)

# Question Answering Prompts
from agent.prompts.question_answering import (
    ANSWER_QUESTION_PROMPT,
    ANSWER_WITHOUT_TOOL_SYSTEM_PROMPT,
    ANSWER_WITH_TOOL_SYSTEM_PROMPT,
    DECOMPOSE_QUESTION_PROMPT,
    DECOMPOSE_SYSTEM_PROMPT,
)

__all__ = [
    # Argument Generation
    "ARGUMENT_GENERATION_SYSTEM_PROMPT",
    "PRO_ARGUMENTS_USER_PROMPT",
    "CONTRA_ARGUMENTS_USER_PROMPT",
    # Argument Critique
    "DEVILS_ADVOCATE_PRO_SYSTEM_PROMPT",
    "DEVILS_ADVOCATE_INDIVIDUAL_PRO_ARGUMENT_USER_PROMPT",
    "DEVILS_ADVOCATE_CONTRA_SYSTEM_PROMPT",
    "DEVILS_ADVOCATE_INDIVIDUAL_CONTRA_ARGUMENT_USER_PROMPT",
    # Argument Evaluation
    "CRITERIA_MAPPING",
    "SINGLE_ARGUMENT_EVALUATION_SYSTEM_PROMPT",
    "EVALUATE_SINGLE_ARGUMENT_USER_PROMPT",
    # Argument Refinement
    "REFINE_PRO_ARGUMENT_SYSTEM_PROMPT",
    "REFINE_PRO_ARGUMENTS_USER_PROMPT",
    "REFINE_CONTRA_ARGUMENT_SYSTEM_PROMPT",
    "REFINE_CONTRA_ARGUMENTS_USER_PROMPT",
    # Question Answering
    "DECOMPOSE_SYSTEM_PROMPT",
    "DECOMPOSE_QUESTION_PROMPT",
    "ANSWER_WITH_TOOL_SYSTEM_PROMPT",
    "ANSWER_WITHOUT_TOOL_SYSTEM_PROMPT",
    "ANSWER_QUESTION_PROMPT",
]
