"""Pydantic schemas for LLM structured outputs.

These schemas define the expected structure of LLM responses
when using structured output mode.
"""

from pydantic import BaseModel, Field


class ArgumentOutput(BaseModel):
    """Single argument generated by the LLM."""

    content: str = Field(description="The argument text")
    qa_indices: list[int] = Field(
        description="Indices of Q&A pairs used to support this argument"
    )


class ArgumentsOutput(BaseModel):
    """Multiple arguments generated by the LLM."""

    arguments: list[ArgumentOutput]


class CriterionScore(BaseModel):
    """Score for a single evaluation criterion."""

    score: int
    reasoning: str


class SingleArgumentScore(BaseModel):
    """All 14 criterion scores for evaluating an argument."""

    scores: list[CriterionScore]


class ArgumentCritique(BaseModel):
    """Devil's advocate critique of an argument."""

    critique: str


class IndividualRefinedArgumentOutput(BaseModel):
    """Refined argument after incorporating feedback."""

    content: str = Field(description="The refined argument text (one paragraph)")
    qa_indices: list[int] = Field(
        description="Indices of Q&A pairs used to support this argument"
    )
